version: '3.8'

services:
  # Spring Boot 애플리케이션
  spring-app:
    image: ${SPRING_APP_IMAGE:-spring-app:latest}
    container_name: spring-app-container
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=${DEPLOYMENT_ENV:-production}
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/prod
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - JAVA_OPTS=-Xms512m -Xmx1024m -XX:+UseG1GC
      - TZ=Asia/Seoul
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - spring-network

  # MySQL 데이터베이스
  mysql:
    image: mysql:8.0
    container_name: spring-app-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prod
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - spring-network

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local

networks:
  spring-network:
    driver: bridge