version: '3.8'

services:
  fastapi-app:
    build:
      context: .
    image: fastapi-app:latest
    container_name: fastapi-app-container
    restart: always
    ports:
      - "8001:8001"
    environment:
      - TZ=Asia/Seoul
    volumes:
      # - ./logs:/app/fast-api-logs
      - ./results_debug:/app/results_debug   # 결과 폴더 영구 보관/호스트에서 바로 확인
    networks:
      - ai-network
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8001 --reload"

networks:
  ai-network:
    driver: bridge