// src/sockets/socketTypes.js

export const SOCKET_TYPES = {
    // 클라이언트 → 서버
    JOIN_ROOM: "JOIN_ROOM",
    LEAVE_ROOM: "LEAVE_ROOM",
    START_GAME: "START_GAME",
    DRAW_DATA: "DRAW_DATA",
    SUBMIT_ANSWER: "SUBMIT_ANSWER",

    USER_TEAM_CHANGE: "USER_TEAM_CHANGE",        // 팀 변경
    USER_READY_CHANGE: "USER_READY_CHANGE",      // 레디 상태 변경
    USER_FORCED_REMOVE: "USER_FORCED_REMOVE",    // 강제 퇴장
    CHAT: "CHAT",                                 // 채팅 (예정)
  
    // 게임 흐름 제어
    TURN_OVER: "TURN_OVER",
    ROUND_OVER: "ROUND_OVER",
    GAME_OVER: "GAME_OVER",
  
    // 서버 → 클라이언트
    ROOM_JOINED: "ROOM_JOINED",
    PLAYER_LEFT: "PLAYER_LEFT",
    GAME_STARTED: "GAME_STARTED",
    ROUND_START: "ROUND_START",
    DRAWING_TURN: "DRAWING_TURN",
    DRAW_BROADCAST: "DRAW_BROADCAST",
    ANSWER_INPUT_START: "ANSWER_INPUT_START",
    ANSWER_RESULT: "ANSWER_RESULT",
    SCORE_UPDATE: "SCORE_UPDATE",
    TIMER_START: "TIMER_START",
    TIMER_END: "TIMER_END",
    TIME_UPDATE: "TIME_UPDATE",
  
    // 에러
    ERROR: "ERROR"
  };